seed: 1
device: auto                  # 'auto', 'cpu', 'cuda'
outdir: outputs/exp_singlehead_gd_correct/          # create new folder if I want to save a specific experiment results

tasks: ["dm1"]                # e.g., ["dm1", "dms"]

data:
  source: cached             # "online", "cached"
  batch_size: 512
  seq_len: 20

  cache:
    num_batches: 2000
    val_frac: 0.1
    build_if_missing: true 
    seed: 7
    paths:                 
      dm1: outputs/cache/dm1_2000x128x350.npz

model:
  hidden_size: 256
  exc_frac: 0.8
  spectral_radius: 1.2
  input_scale: 1.0
  leak: 0.2               # (0,1]
  nonlinearity: softplus  # softplus | tanh
  readout: all        # e_only | all

optim:
  algorithm: gd               # 'eg' (EG on W_hh + GD on others), 'gd' (GD everywhere)
  eg:
    lr: 0.5
    momentum: 0.0
    weight_decay: 1e-5
    min_magnitude: 1e-6
  gd:
    lr: 0.05
    momentum: 0.9
    weight_decay: 1e-5

train:
  num_epochs: 10
  steps_per_epoch: 500        # minibatches (online draw) per epoch
  val_batches: 10             # per task validation batches at epoch end
  grad_clip: 1.0
  input_noise_std: 0.0
  fixdown_weight: 0.1
  spectral_renorm_every: 0
  mask_threshold: 0.5
  task_sampling: round_robin  # 'round_robin', 'random'
  task_weights: []            # used when task_sampling == 'random'; [] => uniform
