seed: 1
device: auto                  # 'auto', 'cpu', 'cuda'
outdir: outputs/train_all/          # create new folder if I want to save a specific experiment results

tasks: ["dm1", "dm1seqr", "dm1seql", "dm2", "dm2seqr", "dm2seql", "ctxdm1", "ctxdm1seqr", "ctxdm1seql", "ctxdm2", "ctxdm2seqr", "ctxdm2seql", "multidm", "multidmseqr", "multidmseql", "dlydm1", "dlydm1seqr", "dlydm1seql", "dlydm1intr", "dlydm1intl", "dlydm1intseq", "dlydm2", "dlydm2seqr", "dlydm2seql", "dlydm2intr", "dlydm2intl", "dlydm2intseq", "ctxdlydm1", "ctxdlydm1seqr", "ctxdlydm1seql", "ctxdlydm1intr", "ctxdlydm1intl", "ctxdlydm1intseq", "ctxdlydm2", "ctxdlydm2seqr", "ctxdlydm2seql", "ctxdlydm2intr", "ctxdlydm2intl", "ctxdlydm2intseq", "multidlydm", "multidlydmseqr", "multidlydmseql", "multidlydmintr", "multidlydmintl", "multidlydmintseq"]

data:
  source: online             # "online", "cached"
  batch_size: 256
  seq_len: 350

  cache:
    num_batches: 128
    val_frac: 0.1
    build_if_missing: true 
    seed: 7
    paths:                 
      dm1: outputs/cache/dm1_fast.npz

model:
  hidden_size: 256
  exc_frac: 0.8
  spectral_radius: 1.2
  input_scale: 1.0
  leak: 0.9               # (0,1]
  nonlinearity: softplus  # softplus | tanh
  readout: all        # e_only | all
  softplus_beta: 10.0
  softplus_threshold: 20.0

optim:
  algorithm: eg               # 'eg' (EG on W_hh + GD on others), 'gd' (GD everywhere)
  eg:
    lr: 0.1
    momentum: 0.0
    weight_decay: 1e-5
    min_magnitude: 1e-6
  gd:
    lr: 0.05
    momentum: 0.9
    weight_decay: 1e-5

train:
  num_epochs: 200              # set to 20 
  steps_per_epoch: 1000       #  minibatches (online draw) per epoch
  val_batches: 20             # per task validation batches at epoch end
  grad_clip: 1.0
  input_noise_std: 0.0
  fixdown_weight: 0.5
  spectral_renorm_every: 0
  mask_threshold: 0.5
  task_sampling: round_robin  # 'round_robin', 'random'
  task_weights: []            # used when task_sampling == 'random'; [] => uniform

  row_sum_zero:
    enabled: true        # or false to turn off
    weight: 0.1         # try 0.01–0.1; tune per your scale
    per_sign: true       # penalize E and I row-sums separately