seed: 1
device: auto                  # 'auto', 'cpu', 'cuda'
outdir: outputs/ablation_gd_1/row_sum/0   

tasks: ["dm1"]                # e.g., ["dm1", "dms"]

data:
  source: cached             # "online", "cached"
  batch_size: 128
  seq_len: 80

  cache:
    num_batches: 128
    val_frac: 0.1
    build_if_missing: true 
    seed: 7
    paths:                 
      dm1: outputs/cache/dm1_fast.npz

model:
  hidden_size: 256
  exc_frac: 0.8
  spectral_radius: 1.2
  input_scale: 1.0
  leak: 0.9              
  nonlinearity: softplus  # softplus | tanh
  readout: all            # e_only | all
  softplus_beta: 10.0
  softplus_threshold: 20.0

optim:
  algorithm: gd  
  eg:
    lr: 0.2
    momentum: 0.0
    weight_decay: 1e-5
    min_magnitude: 1e-6
  gd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-5

train:
  num_epochs: 10         
  steps_per_epoch: 250   
  val_batches: 20  
  grad_clip: 1.0
  input_noise_std: 0.0
  fixdown_weight: 0.5
  spectral_renorm_every: 0
  mask_threshold: 0.5
  task_sampling: round_robin  # 'round_robin', 'random'
  task_weights: []            # used when task_sampling == 'random'; [] => uniform

  row_sum_zero:
    enabled: false   
    weight: 0     
    per_sign: true    