seed: 1
outdir: outputs/fp_runs/    
tasks: ["dm1"]             

data:
  source: cached             # "online" or "cached"
  batch_size: 128
  seq_len: 80

  cache:
    num_batches: 128
    val_frac: 0.1
    build_if_missing: true
    seed: 7
    paths:
      dm1: outputs/cache/dm1_fast.npz 

model:
  hidden_size: 256
  exc_frac: 0.8
  spectral_radius: 1.2
  input_scale: 1.0
  leak: 1
  nonlinearity: softplus
  readout: all
  softplus_beta: 8.0
  softplus_threshold: 20.0

optim:
  algorithm: gd 
  gd:
    lr_gd: 0.01
    momentum: 0.9
    weight_decay: 1e-5

train:
  num_epochs: 20
  steps_per_epoch: 200
  val_batches: 20
  grad_clip: 1.0
  input_noise_std: 0.0
  fixdown_weight: 0.5
  spectral_renorm_every: 0
  mask_threshold: 0.5
  task_sampling: round_robin
  task_weights: []

fixed_points:
  eps_unit: 0.03           # near-unit eigenvalue threshold
  dedup_eps: 0.01          # DBSCAN radius (state space)
  solver:
    max_iter: 800
    tol: 1e-6
    alpha: 1.0             # step size for the h-optimizer (not the leak!)
    backtrack_beta: 0.5
    backtrack_c: 1e-4
  rollout:
    batch: 256
    seq_len: 60
    context_channels:
      clamp: true          # clamp channels for all timesteps
      memory: 0            # adjust indices to your env
      anti: -1
      rule_mem: -1
  eval:
    outdir: eval/fixed_points
    z_logit: 0      
