# ===== experiment.yaml =====
seed: 1
device: auto
outdir: outputs/dlygo_test_4/

tasks: ["dlygo"]                 # keep your training list; ring typically needs a circular/angle task (see notes below)

data:
  source: online               # "online", "cached"
  batch_size: 128
  seq_len: 350

  cache:
    num_batches: 128
    val_frac: 0.1
    build_if_missing: true 
    seed: 7
    paths:
      dlygo: outputs/cache/dlygo_fast.npz

model:
  hidden_size: 256
  exc_frac: 0.8
  spectral_radius: 1.05
  input_scale: 1.0
  leak: 0.8                     # used consistently in FP solver & rollouts
  nonlinearity: tanh
  readout: all
  softplus_beta: 5.0         # used consistently in FP solver & rollouts
  softplus_threshold: 20.0

optim:
  algorithm: gd
  eg:
    lr: 0.1
    momentum: 0.0
    weight_decay: 1e-5
    min_magnitude: 1e-6
  gd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 1e-5

train:
  num_epochs: 20
  steps_per_epoch: 300
  val_batches: 20
  grad_clip: 1.0
  input_noise_std: 0.0
  fixdown_weight: 0.1
  spectral_renorm_every: 0
  mask_threshold: 0.5
  task_sampling: round_robin
  task_weights: []

  row_sum_zero:
    enabled: false
    weight: 0.5
    per_sign: false