outdir: outputs/runs/smoke/eg/pI=0.35/seed=000
optim: eg
pI: 0.35
seed: 0
task: dm1
hidden: 256
epochs: 10
steps: 500
seq_len: 350
batch: 128
spectral_radius: 1.2
input_scale: 1.0
lr_eg: 1.5
lr_gd: 0.01
device: auto
label_smoothing: 0.1
fixdown_weight: 0.05
grad_clip: 1.0
val_batches: 50
mask_threshold: 0.5
input_noise_std: 0.1
renorm_every: 1000
