exp_id: "exp_ei_credit"
out_dir: outputs/ei_gradient/test

# Single head checkpoints only
checkpoint: "outputs/row_sum/singlehead_epoch010.pt"
#checkpoint: "outputs/final/model_perf/gd_t_1_H_256/singlehead_epoch002.pt"

seeds: [1, 2, 3]

ei_from_checkpoint: true  
activation: "softplus"

task: "dm1"
split: "valid"
batch_size: 16
max_batches: 4
device: "cpu"

time_window:
  start: null
  end: null
  stride: 1

save:
  ht: true
  ut: false
  grad_h: true
  grad_x: true
