P: 1000
N1: 10
N3: 10
noise_std: 0.01
steps: 400
record_every: 1
eta_eg: 0.1
eta_gd: 0.05
init: 1       # choose from 1 to 7 (2 is the only not sign matched initialisation)
seed: 1
num_modes: 10
out: null
csv_out: null
no_show: false
plot_curves: both # Choice of eg, gd, both
break_order: false
mean: true
num_runs: 200
outdir: outputs/one_layer
out: plot.png